<a href="https://colab.research.google.com/github/rlagosb/GastricCancerIncidence/blob/main/1_Participants_and_trajectories.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook presents an analysis of gastric cancer incidence, the demographic characteristics of the study and target population, patient trajectories, and in-hospital survival. The objective is to provide detailed information for researchers interested in the epidemiology of gastric cancer and its outcomes.

The content includes:

*   **Data loading and preparation:** Data on populations, hospital discharges, and deaths related to digestive cancer are loaded and processed.
*   **Characterization of participants (Table 1):** A descriptive table of the study and target population is presented, stratified by sex, age ranges, rurality, and type of health insurance (Fonasa/Isapre).
*   **Gastric Cancer Trajectories:** Sequences of events (discharge, death) for patients are analyzed, including a Sankey diagram to visualize transition flows.
*   **Trajectories by province:** Deaths without hospitalization and 5-year survival by province and five-year period are examined to provide a regional perspective of the results.

# Setup

In [5]:
import pandas as pd
import plotly.graph_objects as go

path_cubo = 'https://raw.githubusercontent.com/rlagosb/GastricCancerIncidence/main/Data/'

# load main table
cubo = pd.read_parquet(path_cubo + 'CUBO_CANCER_DIGESTIVO.parquet')
cubo = cubo[cubo.Provincia!=122] #excluir provincia Antártica
print(cubo.info(), end='\n\n')

# load provinces
provincias = (cubo[['Region','Provincia','Nombre Region','Nombre Provincia']].
              drop_duplicates())

# Cargar egresos-defunciones desagregados
egresosDefs = pd.read_parquet(path_cubo + 'EGRESOS_DEFUNCIONES_DESAGREGADOS.parquet')
egresosDefs = egresosDefs[egresosDefs.Provincia!=122] #excluir provincia Antártica
print(egresosDefs.info())

<class 'pandas.core.frame.DataFrame'>
Index: 24156 entries, 0 to 24947
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Provincia             24156 non-null  int64
 1   Nombre Provincia      24156 non-null  object
 2   Nombre Region         24156 non-null  object
 3   Region                24156 non-null  int64
 4   Macrorregion          24156 non-null  object
 5   Año                   24156 non-null  int64
 6   Sexo                  24156 non-null  object
 7   RangoEdad10           24156 non-null  object
 8   RangoEdad4080         24156 non-null  object
 9   MedianaRangoEdad10    24156 non-null  float64
 10  MedianaRangoEdad4080  24156 non-null  float64
 11  Poblacion             24156 non-null  int64
 12  PoblacionRural        24156 non-null  int64
 13  A                     24156 non-null  int64
 14  B                     24156 non-null  int64
 15  C                     24156 non-null  int64
 16  D                     24156 non-null  int64
 17  Fonasa                24156 non-null  int64
 18  Isapre                24156 non-null  int64
 19  Categoria             24156 non-null  object
 20  Cancer                24156 non-null  object
 21  RPC                   24156 non-null  int64
 22  Casos                 24156 non-null  int64
 23  Defunciones           24156 non-null  int64
 24  EgresosDefs           24156 non-null  int64
 25  Egresos               24156 non-null  int64
dtypes: float64(2), int64(16), object(8)
memory usage: 5.0+ MB
None

<class 'pandas.core.frame.DataFrame'>
Index: 179850 entries, 0 to 179858
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   idPersona    177498 non-null  object
 1   Sexo         179850 non-null  int64
 2   Año          179850 non-null  int64
 3   Edad         179850 non-null  int64
 4   Provincia    179500 non-null  float64
 5   Categoria    179850 non-null  object
 6   Trayectoria  179850 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 11.0+ MB
None

# Participants
Study and objetive populations in person-years

In [6]:
def get_participantes(periodo_objetivo=range(2003,2025)):

  # Agrupar edad por rango
  metricas = ['Poblacion','PoblacionRural','Fonasa','A','B','C','D','Isapre']
  df = cubo.groupby(['Año','Sexo','RangoEdad4080','RPC','Provincia'],observed=True)[metricas].sum().reset_index()

  # Generate study (1) and objective (2) populations
  df1 = df[df.RPC>0].copy()
  df2 = df[df.Año.isin(periodo_objetivo)].copy()
  df1['Grupo'] = 'Estudio'
  df2['Grupo'] = 'Objetivo'
  df = pd.concat([df1,df2])

  # Contar Años
  agg_dict = {metric: 'sum' for metric in metricas}
  agg_dict['Año'] = 'count'
  df = (df.groupby(['Sexo', 'RangoEdad4080','RPC','Provincia','Grupo'], observed=True).agg(agg_dict).reset_index().
        rename(columns={'Año':'N_Años'}))

  return df

poblaciones = get_participantes()
poblaciones

,Sexo,RangoEdad4080,RPC,Provincia,Grupo,Poblacion,PoblacionRural,Fonasa,A,B,C,D,Isapre,N_Años
0,Hombre,"[0, 40)",0,11,Objetivo,2209190,34920,1453505,405604,340120,302172,405609,542627,22
1,Hombre,"[0, 40)",0,14,Objetivo,175192,81561,122398,50237,23944,18164,30277,13795,22
2,Hombre,"[0, 40)",0,21,Objetivo,1287422,28215,773474,144760,190287,154054,284451,355918,9
3,Hombre,"[0, 40)",0,22,Objetivo,567792,31083,377674,55864,88600,73766,159624,155859,9
4,Hombre,"[0, 40)",0,23,Objetivo,92156,4668,43295,15223,7825,6584,13663,17205,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,Mujer,"[80, 120)",6,72,Objetivo,5087,1336,4332,27,3955,149,201,51,3
1004,Mujer,"[80, 120)",6,73,Estudio,14774,3929,7950,53,11740,517,582,320,3
1005,Mujer,"[80, 120)",6,73,Objetivo,14774,3929,7950,53,11740,517,582,320,3
1006,Mujer,"[80, 120)",6,74,Estudio,16191,5496,13381,155,13499,564,583,277,3
1007,Mujer,"[80, 120)",6,74,Objetivo,16191,5496,13381,155,13499,564,583,277,3

## 📊 Table 1

Based on recomendations of Hayes-Larson, Eleanor, Katrina L. Kezios, Stephen J. Mooney, y Gina Lovasi. «Who Is in This Study, Anyway? Guidelines for a Useful Table 1». Journal of Clinical Epidemiology 114 (octubre de 2019): 125-32. https://doi.org/10.1016/j.jclinepi.2019.06.011.

In [8]:
def subtabla(variable, RangoEdad, df) -> pd.DataFrame:

  # sumar total población

  match variable:
    case 'Total':
      df = df.groupby(['Grupo'],observed=True)['Poblacion'].sum().reset_index()
      df['Total'] = df['Grupo'] + ' N=' + df['Poblacion'].astype(str)
      return df.Total.to_list()

    case 'Sexo' | 'RangoEdad4080':
      df = df.pivot_table(index=variable, values='Poblacion',columns='Grupo',aggfunc='sum',margins=True)
      # transform to percentages
      df['Estudio'] = df['Estudio']/df.loc['All','Estudio']
      df['Objetivo'] = df['Objetivo']/df.loc['All','Objetivo']
      return df.drop('All').drop(columns='All').reset_index(names=variable)

    case 'Ruralidad':
      df = df.groupby(['Grupo'], observed=True)[['PoblacionRural','Poblacion']].sum().reset_index()
      df['Ruralidad'] = df['PoblacionRural']/df['Poblacion']
      return df[['Grupo','Ruralidad']].set_index('Grupo').T

    case 'Beneficiarios':
      tramos = ['A','B','C','D','Isapre']
      df = df.groupby(['Grupo'], observed=True)[['Poblacion'] + tramos].sum().reset_index()
      for col in tramos:
        df[col] = df[col]/df['Poblacion']
      return df.set_index('Grupo').T.drop('Poblacion').reset_index(names='Beneficiarios')


def get_tabla1(RangoEdad, df):

  # Agrupar tablas
  tabla = pd.DataFrame()
  for variable in ['Sexo',RangoEdad,'Ruralidad','Beneficiarios']:
    tabla_var = subtabla(variable, RangoEdad, df)
    tabla_var['Variable'] = variable
    tabla_var.rename(columns={variable:'Valor'},inplace=True)
    tabla = pd.concat([tabla, tabla_var])

  # Formatear índice y columnas
  tabla.set_index(['Variable','Valor'], inplace=True)
  tabla.columns = subtabla('Total', 'RangoEdad4080', poblaciones)

  return (tabla*100).round(1)


tabla1 = get_tabla1('RangoEdad4080', poblaciones)
tabla1

                         Estudio N=29348519  Objetivo N=394057268
Variable      Valor
Sexo          Hombre                   49.6                  49.3
              Mujer                    50.4                  50.7
RangoEdad4080 [0, 40)                  61.9                  59.8
              [40, 50)                 13.9                  13.7
              [50, 60)                 11.1                  11.5
              [60, 70)                  7.1                   8.0
              [70, 80)                  4.1                   4.7
              [80, 120)                 2.0                   2.4
Ruralidad     NaN                      15.5                  12.3
Beneficiarios A                        18.7                  19.6
              B                        20.4                  26.4
              C                        10.1                  12.5
              D                        12.1                  16.4
              Isapre                   17.3                  17.9

# Trajectories

In [9]:
#@title Cargar Eventos

# Eventos sin id Persona o Provincia
egresosDefs['SinIdPersona'] = (egresosDefs.idPersona.isna())
egresosDefs['SinProvincia'] = (egresosDefs.Provincia==999)

print(egresosDefs.reset_index().pivot_table(index='Categoria',
                                      columns=['Trayectoria','SinProvincia','SinIdPersona'],
                                      values='index',
                                      aggfunc='count',
                                      margins=True))

# Filtrar eventos sin id Persona o Provincia
egresosDefs = egresosDefs[lambda x: ~x.SinProvincia & ~x.SinIdPersona]

Trayectoria  Defuncion  Egreso           All
SinProvincia     False   False
SinIdPersona     False   False  True
Categoria
C16              69969  107529  2352  179850
All              69969  107529  2352  179850

In [10]:
#@title Cargar Trayectorias de Personas

def cargar_trayectorias_personas(df):
  # Concatenar eventos CG de una persona
  def serie_trayectorias(serie):
    serie = serie.astype(str) + '>'
    x = serie.cumsum()
    return x.iloc[-1] # Return only the last cumulative trajectory

  trayectorias = (df.groupby(['idPersona'], dropna=True)['Trayectoria'].
                  apply(serie_trayectorias).str[:-1].  # agrupar eventos de cada persona
                  value_counts(dropna=False))
  return trayectorias.reset_index()

trayectorias = cargar_trayectorias_personas(egresosDefs.copy())

print('Top 5 trayectorias\n:', trayectorias.head(5), end='\n\n')

print(trayectorias['count'].sum(), 'personas con trayectorias de CG,\n',
      trayectorias[lambda x: x.Trayectoria.str.contains('Defuncion')]['count'].sum()*100/trayectorias['count'].sum(), '% con defunción\n',
      trayectorias[lambda x: x.Trayectoria.str.contains('Egreso')]['count'].sum()*100/trayectorias['count'].sum(), '% con egreso\n',
      trayectorias[lambda x: x.Trayectoria.str.contains('Defuncion') & ~x.Trayectoria.str.contains('Egreso')]['count'].sum()*100/trayectorias['count'].sum(), '% con defunción sin egreso')

Top 5 trayectorias
:                Trayectoria  count
0                Defuncion  33191
1         Egreso>Defuncion  23134
2                   Egreso  19572
3  Egreso>Egreso>Defuncion   7698
4            Egreso>Egreso   4188

96187 personas con trayectorias de CG,
 72.74059904145051 % con defunción
 65.49117864160438 % con egreso
 34.50882135839562 % con defunción sin egreso

In [11]:
#@title 🔀 Figura 1

def diagrama_sankey(trayectorias):

  # Parametrizar transiciones
  for col in ['Disease-free_Hospitalized','Disease-free_Deceased','Hospitalized_Alive','Hospitalized_Deceased']:
    trayectorias[col] = False
  egresoInicio = (trayectorias.Trayectoria.str[:6]=='Egreso')
  conDefuncion = (trayectorias.Trayectoria.str.contains('Defuncion'))
  # Sano>Egreso
  trayectorias.loc[egresoInicio,'Disease-free_Hospitalized'] = True
  # Sano>Defuncion
  trayectorias.loc[trayectorias.Trayectoria.str[:9]=='Defuncion','Disease-free_Deceased'] = True
  # Egreso>Vivo
  trayectorias.loc[egresoInicio & ~conDefuncion,'Hospitalized_Alive'] = True
  # Egreso>Defuncion
  trayectorias.loc[egresoInicio & conDefuncion,'Hospitalized_Deceased'] = True

  arcos = (trayectorias.melt(id_vars=['Trayectoria','count'],
                           value_vars=['Disease-free_Hospitalized','Disease-free_Deceased','Hospitalized_Alive','Hospitalized_Deceased'],
                           var_name='Arco',value_name='Valor')[lambda x: x.Valor].  # dejar sólo transiciones activas
           groupby(['Arco','Valor'])['count'].sum().reset_index())                  # agrupar transiciones
  # separar origen/destino
  arcos[['Source','Target']] = (arcos.Arco.str.split('_',expand=True))

  # Create Sankey diagram https://plotly.com/python/sankey-diagram/
  nodes = pd.concat([arcos['Source'], arcos['Target']]).unique()
  nodes = pd.DataFrame({'name': nodes})
  nodes['id'] = nodes.index
  arcos = arcos.merge(nodes.rename(columns={'name':'Source'}), on='Source', how='left')
  arcos = arcos.merge(nodes.rename(columns={'name':'Target'}), on='Target', how='left', suffixes=('_source', '_target'))

  go.Figure(data=[go.Sankey(
      node=dict(pad=15, thickness=20,
          line=dict(color="black", width=0.5),
          label=nodes['name'],),
      link=dict(
          source=arcos['id_source'],
          target=arcos['id_target'],
          value=arcos['count']))]).show()


diagrama_sankey(trayectorias.copy())

# Trayectorias Provincias

In [12]:
def trayectorias_persona(df):
  df = df[df.idPersona.notna()]

  # Obtener año de egreso y hospitalización por persona
  fa = df[df.Trayectoria=='Defuncion'][['idPersona','Año']].rename(columns={'Año':'AñoDefuncion'})
  eg = df[df.Trayectoria=='Egreso'][['idPersona','Año']].rename(columns={'Año':'AñoEgreso'})
  df = (df.groupby(['idPersona']).agg({'Provincia':'first'}).reset_index().
        merge(eg, on='idPersona', how='outer').
        merge(fa, on='idPersona', how='outer').
        groupby(['idPersona','Provincia']).agg({'AñoEgreso':'min','AñoDefuncion':'max'}).reset_index())

  # Métricas sobrevida
  df['Delta'] = df.AñoDefuncion - df.AñoEgreso
  df.loc[df.AñoDefuncion.isna(), 'sobrevida5'] = True
  df.loc[df.Delta.notna(), 'sobrevida5'] = df[df.Delta.notna()].Delta.apply(lambda x: x>=5)

  # get minimum between AñoEgreso and AñoDefuncion
  df['Quinquenio'] = df[['AñoEgreso','AñoDefuncion']].min(axis=1).apply(lambda x: (x//5)*5)

  df['Defuncion'] = df.AñoDefuncion.notna()
  df['Egreso'] = df.AñoEgreso.notna()
  df['DefuncionSinEgreso'] = df.Defuncion & ~df.Egreso

  df = df.groupby(['Provincia','Quinquenio']).agg({'Delta':'mean','sobrevida5':'sum','Defuncion':'sum','Egreso':'sum','DefuncionSinEgreso':'sum','idPersona':'count'}).reset_index()

  return df

trayectoriasProv = trayectorias_persona(egresosDefs.copy())

## 📊 Defunciones sin hospitalización (Material Sup 3)

In [14]:
# Defunción sin hospitalización por provincia y quinquenio

print('Porcentaje de defunciones sin hospitalización:\n',
      trayectoriasProv.DefuncionSinEgreso.sum()*100/trayectoriasProv.idPersona.sum())

trayectoriasProv['PorcDefSinEgreso'] = trayectoriasProv.DefuncionSinEgreso*100/trayectoriasProv.idPersona

trayectoriasProv[lambda x: x.Quinquenio>2000].\
pivot(columns='Quinquenio',index='Provincia',values='PorcDefSinEgreso').\
merge(provincias, on='Provincia').\
sort_values(by=['Region','Provincia']).\
set_index(['Region','Nombre Region','Nombre Provincia']).drop(columns='Provincia').round(1)

Porcentaje de defunciones sin hospitalización:
 34.54042185662702

                                                                       2005.0  \
Region Nombre Region                             Nombre Provincia
1      Tarapacá                                  Iquique                 67.0
                                                 Tamarugal               77.8
2      Antofagasta                               Antofagasta             32.1
                                                 El Loa                  29.0
                                                 Tocopilla               16.0
3      Atacama                                   Copiapó                 34.6
                                                 Chañaral                23.3
                                                 Huasco                  28.2
4      Coquimbo                                  Elqui                   40.3
                                                 Choapa                  51.3
                                                 Limarí                  39.2
5      Valparaíso                                Valparaíso              25.3
                                                 Isla de Pascua          25.0
                                                 Los Andes               33.3
                                                 Petorca                 37.4
                                                 Quillota                34.9
                                                 San Antonio             38.5
                                                 San Felipe              14.7
                                                 Marga Marga             37.4
6      Libertador General Bernardo O'Higgins     Cachapoal               34.7
                                                 Cardenal Caro           45.8
                                                 Colchagua               38.1
7      Maule                                     Talca                   43.9
                                                 Cauquenes               54.0
                                                 Curicó                  40.0
                                                 Linares                 41.5
8      Biobío                                    Concepción              28.8
                                                 Arauco                  33.4
                                                 Bíobío                  33.2
9      La Araucanía                              Cautín                  38.0
                                                 Malleco                 28.7
10     Los Lagos                                 Llanquihue              29.0
                                                 Chiloé                  45.1
                                                 Osorno                  37.0
                                                 Palena                  30.6
11     Aysén del General Carlos Ibáñez del Campo Coyhaique               38.6
                                                 Aysén                   43.9
                                                 Capitán Prat            60.0
                                                 General Carrera         38.5
12     Magallanes y de la Antártica Chilena      Magallanes              30.8
                                                 Tierra del Fuego        20.0
                                                 Última Esperanza        50.0
13     Metropolitana de Santiago                 Cordillera              24.3
                                                 Chacabuco               39.6
                                                 Maipo                   36.9
                                                 Melipilla               51.5
                                                 Talagante               52.9
                                                 Santiago Norte          32.8
                                                 Santiago Occidente      47.2
                                                 Santiago Central        29.1
                                                 Santiago Oriente        29.6
                                                 Santiago Sur            39.2
                                                 Santiago Sur Oriente    30.3
14     Los Ríos                                  Valdivia                26.3
                                                 Ranco                   24.2
15     Arica y Parinacota                        Arica                   50.9
                                                 Parinacota              33.3
16     Ñuble                                     Diguillín               37.1
                                                 Itata                   46.8
                                                 Punilla                 41.9

                                                                       2010.0  \
Region Nombre Region                             Nombre Provincia
1      Tarapacá                                  Iquique                 47.9
                                                 Tamarugal               11.1
2      Antofagasta                               Antofagasta             42.0
                                                 El Loa                  34.9
                                                 Tocopilla               38.9
3      Atacama                                   Copiapó                 35.1
                                                 Chañaral                20.8
                                                 Huasco                  27.8
4      Coquimbo                                  Elqui                   36.1
                                                 Choapa                  46.8
                                                 Limarí                  49.8
5      Valparaíso                                Valparaíso              24.2
                                                 Isla de Pascua          20.0
                                                 Los Andes               26.0
                                                 Petorca                 44.0
                                                 Quillota                38.9
                                                 San Antonio             42.4
                                                 San Felipe              15.0
                                                 Marga Marga             36.0
6      Libertador General Bernardo O'Higgins     Cachapoal               39.3
                                                 Cardenal Caro           52.8
                                                 Colchagua               36.8
7      Maule                                     Talca                   44.7
                                                 Cauquenes               42.9
                                                 Curicó                  42.0
                                                 Linares                 49.1
8      Biobío                                    Concepción              25.0
                                                 Arauco                  34.4
                                                 Bíobío                  32.7
9      La Araucanía                              Cautín                  38.0
                                                 Malleco                 29.2
10     Los Lagos                                 Llanquihue              30.7
                                                 Chiloé                  38.5
                                                 Osorno                  36.7
                                                 Palena                  31.8
11     Aysén del General Carlos Ibáñez del Campo Coyhaique               29.9
                                                 Aysén                   34.2
                                                 Capitán Prat            60.0
                                                 General Carrera         43.8
12     Magallanes y de la Antártica Chilena      Magallanes              26.7
                                                 Tierra del Fuego         0.0
                                                 Última Esperanza        18.2
13     Metropolitana de Santiago                 Cordillera              24.9
                                                 Chacabuco               33.3
                                                 Maipo                   40.3
                                                 Melipilla               38.9
                                                 Talagante               45.0
                                                 Santiago Norte          34.3
                                                 Santiago Occidente      43.7
                                                 Santiago Central        24.0
                                                 Santiago Oriente        31.6
                                                 Santiago Sur            37.6
                                                 Santiago Sur Oriente    32.2
14     Los Ríos                                  Valdivia                22.7
                                                 Ranco                   40.2
15     Arica y Parinacota                        Arica                   35.3
                                                 Parinacota               0.0
16     Ñuble                                     Diguillín               32.0
                                                 Itata                   39.3
                                                 Punilla                 42.7

                                                                       2015.0  \
Region Nombre Region                             Nombre Provincia
1      Tarapacá                                  Iquique                 38.1
                                                 Tamarugal               47.1
2      Antofagasta                               Antofagasta             47.3
                                                 El Loa                  18.6
                                                 Tocopilla               40.9
3      Atacama                                   Copiapó                 31.3
                                                 Chañaral                38.1
                                                 Huasco                  31.6
4      Coquimbo                                  Elqui                   39.8
                                                 Choapa                  66.3
                                                 Limarí                  48.4
5      Valparaíso                                Valparaíso              27.2
                                                 Isla de Pascua           0.0
                                                 Los Andes               46.2
                                                 Petorca                 44.9
                                                 Quillota                42.2
                                                 San Antonio             43.1
                                                 San Felipe              14.5
                                                 Marga Marga             35.9
6      Libertador General Bernardo O'Higgins     Cachapoal               42.6
                                                 Cardenal Caro           36.4
                                                 Colchagua               43.1
7      Maule                                     Talca                   40.7
                                                 Cauquenes               42.9
                                                 Curicó                  40.2
                                                 Linares                 41.0
8      Biobío                                    Concepción              26.6
                                                 Arauco                  35.8
                                                 Bíobío                  32.2
9      La Araucanía                              Cautín                  34.3
                                                 Malleco                 27.6
10     Los Lagos                                 Llanquihue              24.5
                                                 Chiloé                  38.6
                                                 Osorno                  27.1
                                                 Palena                  33.3
11     Aysén del General Carlos Ibáñez del Campo Coyhaique               24.7
                                                 Aysén                   26.7
                                                 Capitán Prat             0.0
                                                 General Carrera          9.1
12     Magallanes y de la Antártica Chilena      Magallanes              22.1
                                                 Tierra del Fuego         0.0
                                                 Última Esperanza        47.8
13     Metropolitana de Santiago                 Cordillera              17.1
                                                 Chacabuco               34.5
                                                 Maipo                   33.0
                                                 Melipilla               40.9
                                                 Talagante               48.5
                                                 Santiago Norte          32.1
                                                 Santiago Occidente      39.0
                                                 Santiago Central        21.9
                                                 Santiago Oriente        26.3
                                                 Santiago Sur            39.0
                                                 Santiago Sur Oriente    35.8
14     Los Ríos                                  Valdivia                27.6
                                                 Ranco                   41.9
15     Arica y Parinacota                        Arica                   26.8
                                                 Parinacota               0.0
16     Ñuble                                     Diguillín               33.6
                                                 Itata                   23.4
                                                 Punilla                 39.9

                                                                       2020.0
Region Nombre Region                             Nombre Provincia
1      Tarapacá                                  Iquique                 35.9
                                                 Tamarugal               37.5
2      Antofagasta                               Antofagasta             29.1
                                                 El Loa                  30.4
                                                 Tocopilla               29.6
3      Atacama                                   Copiapó                 30.8
                                                 Chañaral                40.7
                                                 Huasco                  30.1
4      Coquimbo                                  Elqui                   37.3
                                                 Choapa                  48.2
                                                 Limarí                  48.4
5      Valparaíso                                Valparaíso              31.9
                                                 Isla de Pascua          33.3
                                                 Los Andes               47.0
                                                 Petorca                 36.8
                                                 Quillota                45.2
                                                 San Antonio             47.2
                                                 San Felipe              28.8
                                                 Marga Marga             38.5
6      Libertador General Bernardo O'Higgins     Cachapoal               43.4
                                                 Cardenal Caro           56.7
                                                 Colchagua               42.2
7      Maule                                     Talca                   41.6
                                                 Cauquenes               34.0
                                                 Curicó                  35.7
                                                 Linares                 44.7
8      Biobío                                    Concepción              30.5
                                                 Arauco                  34.4
                                                 Bíobío                  33.4
9      La Araucanía                              Cautín                  43.0
                                                 Malleco                 41.8
10     Los Lagos                                 Llanquihue              18.4
                                                 Chiloé                  30.2
                                                 Osorno                  20.2
                                                 Palena                  31.2
11     Aysén del General Carlos Ibáñez del Campo Coyhaique               32.9
                                                 Aysén                   25.0
                                                 Capitán Prat            50.0
                                                 General Carrera         27.3
12     Magallanes y de la Antártica Chilena      Magallanes              27.2
                                                 Tierra del Fuego        33.3
                                                 Última Esperanza        28.6
13     Metropolitana de Santiago                 Cordillera              25.6
                                                 Chacabuco               37.5
                                                 Maipo                   41.4
                                                 Melipilla               41.4
                                                 Talagante               43.9
                                                 Santiago Norte          28.8
                                                 Santiago Occidente      34.5
                                                 Santiago Central        24.6
                                                 Santiago Oriente        25.5
                                                 Santiago Sur            40.5
                                                 Santiago Sur Oriente    33.5
14     Los Ríos                                  Valdivia                31.9
                                                 Ranco                   41.8
15     Arica y Parinacota                        Arica                   23.6
                                                 Parinacota               0.0
16     Ñuble                                     Diguillín               41.8
                                                 Itata                   42.1
                                                 Punilla                 37.5

## Sobrevida Intrahospitalaria (Material Sup 4)

In [16]:
# add colum percentage sobrevida5

# Agregar total nacional
sobre = pd.concat([trayectoriasProv.copy(),
                  trayectoriasProv.groupby(['Quinquenio'])[['sobrevida5','idPersona']].sum().reset_index()])
# Excluir último quinquenio
sobre = sobre[sobre.Quinquenio<2020]

# Calcular sobrevida 5 años
sobre['PorcSobrevida5'] = (sobre.sobrevida5*100.0/sobre.idPersona).round(1)

print(f'Sobrevida a 5 años nacional:\n {sobre[sobre.Provincia.isna()].sobrevida5.sum()/sobre[sobre.Provincia.isna()].idPersona.sum()*100} %')

# Calcular sobrevida por provincia
sobre = sobre.pivot(index='Provincia', columns='Quinquenio', values='PorcSobrevida5').\
merge(provincias, on='Provincia', how='left').\
sort_values(by=['Region','Provincia']).\
drop(columns='Provincia').set_index(['Region','Nombre Region','Nombre Provincia'])

for col in sobre.columns:
  sobre[col] = sobre[col].astype(float).round(1)

pd.set_option('display.max_rows', None)
display(sobre)

Sobrevida a 5 años nacional:
 26.565981348311606 %

                                                                       2000.0  \
Region Nombre Region                             Nombre Provincia
1.0    Tarapacá                                  Iquique                 14.1
                                                 Tamarugal               33.3
2.0    Antofagasta                               Antofagasta             23.7
                                                 El Loa                  36.8
                                                 Tocopilla               11.1
3.0    Atacama                                   Copiapó                 40.0
                                                 Chañaral                52.9
                                                 Huasco                  12.8
4.0    Coquimbo                                  Elqui                   26.3
                                                 Choapa                  22.2
                                                 Limarí                  20.4
5.0    Valparaíso                                Valparaíso              25.6
                                                 Isla de Pascua           NaN
                                                 Los Andes               32.0
                                                 Petorca                 25.8
                                                 Quillota                27.1
                                                 San Antonio             15.3
                                                 San Felipe              24.7
                                                 Marga Marga             35.2
6.0    Libertador General Bernardo O'Higgins     Cachapoal               20.5
                                                 Cardenal Caro           29.4
                                                 Colchagua               17.4
7.0    Maule                                     Talca                   16.4
                                                 Cauquenes               10.0
                                                 Curicó                  17.1
                                                 Linares                 16.8
8.0    Biobío                                    Concepción              41.2
                                                 Arauco                  38.6
                                                 Bíobío                  23.2
9.0    La Araucanía                              Cautín                  17.5
                                                 Malleco                 20.9
10.0   Los Lagos                                 Llanquihue              22.7
                                                 Chiloé                  14.8
                                                 Osorno                  26.7
                                                 Palena                  57.1
11.0   Aysén del General Carlos Ibáñez del Campo Coyhaique               16.7
                                                 Aysén                   41.2
                                                 Capitán Prat            50.0
                                                 General Carrera          0.0
12.0   Magallanes y de la Antártica Chilena      Magallanes              25.4
                                                 Tierra del Fuego        12.5
                                                 Última Esperanza        12.5
13.0   Metropolitana de Santiago                 Cordillera              35.6
                                                 Chacabuco               26.1
                                                 Maipo                   21.9
                                                 Melipilla               23.9
                                                 Talagante               18.8
                                                 Santiago Norte          30.3
                                                 Santiago Occidente      24.9
                                                 Santiago Central        29.3
                                                 Santiago Oriente        34.0
                                                 Santiago Sur            25.9
                                                 Santiago Sur Oriente    26.8
14.0   Los Ríos                                  Valdivia                27.5
                                                 Ranco                   31.7
15.0   Arica y Parinacota                        Arica                   10.3
                                                 Parinacota               NaN
16.0   Ñuble                                     Diguillín               39.3
                                                 Itata                   20.4
                                                 Punilla                 29.0
NaN    NaN                                       NaN                     26.7

                                                                       2005.0  \
Region Nombre Region                             Nombre Provincia
1.0    Tarapacá                                  Iquique                 13.3
                                                 Tamarugal               11.1
2.0    Antofagasta                               Antofagasta             29.2
                                                 El Loa                  22.0
                                                 Tocopilla               32.0
3.0    Atacama                                   Copiapó                 31.4
                                                 Chañaral                20.0
                                                 Huasco                  16.5
4.0    Coquimbo                                  Elqui                   23.8
                                                 Choapa                  15.9
                                                 Limarí                  16.7
5.0    Valparaíso                                Valparaíso              28.2
                                                 Isla de Pascua          25.0
                                                 Los Andes               25.0
                                                 Petorca                 19.8
                                                 Quillota                25.0
                                                 San Antonio             20.1
                                                 San Felipe              30.6
                                                 Marga Marga             29.0
6.0    Libertador General Bernardo O'Higgins     Cachapoal               24.8
                                                 Cardenal Caro           12.5
                                                 Colchagua               23.5
7.0    Maule                                     Talca                   19.8
                                                 Cauquenes               10.0
                                                 Curicó                  17.8
                                                 Linares                 15.7
8.0    Biobío                                    Concepción              27.6
                                                 Arauco                  30.2
                                                 Bíobío                  21.8
9.0    La Araucanía                              Cautín                  33.2
                                                 Malleco                 27.8
10.0   Los Lagos                                 Llanquihue              23.7
                                                 Chiloé                  22.3
                                                 Osorno                  19.7
                                                 Palena                  22.2
11.0   Aysén del General Carlos Ibáñez del Campo Coyhaique               33.7
                                                 Aysén                   36.6
                                                 Capitán Prat            20.0
                                                 General Carrera         23.1
12.0   Magallanes y de la Antártica Chilena      Magallanes              37.0
                                                 Tierra del Fuego        40.0
                                                 Última Esperanza        26.9
13.0   Metropolitana de Santiago                 Cordillera              33.7
                                                 Chacabuco               29.2
                                                 Maipo                   24.4
                                                 Melipilla               25.7
                                                 Talagante               27.9
                                                 Santiago Norte          27.2
                                                 Santiago Occidente      30.8
                                                 Santiago Central        32.7
                                                 Santiago Oriente        32.0
                                                 Santiago Sur            25.9
                                                 Santiago Sur Oriente    30.0
14.0   Los Ríos                                  Valdivia                26.1
                                                 Ranco                   26.9
15.0   Arica y Parinacota                        Arica                   21.5
                                                 Parinacota               0.0
16.0   Ñuble                                     Diguillín               25.8
                                                 Itata                   22.3
                                                 Punilla                 16.8
NaN    NaN                                       NaN                     26.8

                                                                       2010.0  \
Region Nombre Region                             Nombre Provincia
1.0    Tarapacá                                  Iquique                 16.4
                                                 Tamarugal               22.2
2.0    Antofagasta                               Antofagasta             26.9
                                                 El Loa                  30.2
                                                 Tocopilla               16.7
3.0    Atacama                                   Copiapó                 28.7
                                                 Chañaral                45.8
                                                 Huasco                  30.0
4.0    Coquimbo                                  Elqui                   25.3
                                                 Choapa                  19.1
                                                 Limarí                  13.9
5.0    Valparaíso                                Valparaíso              25.5
                                                 Isla de Pascua          40.0
                                                 Los Andes               37.0
                                                 Petorca                 23.9
                                                 Quillota                23.4
                                                 San Antonio             20.5
                                                 San Felipe              35.7
                                                 Marga Marga             22.8
6.0    Libertador General Bernardo O'Higgins     Cachapoal               24.1
                                                 Cardenal Caro           18.9
                                                 Colchagua               28.9
7.0    Maule                                     Talca                   21.1
                                                 Cauquenes               14.3
                                                 Curicó                  16.8
                                                 Linares                 14.6
8.0    Biobío                                    Concepción              24.1
                                                 Arauco                  25.5
                                                 Bíobío                  24.3
9.0    La Araucanía                              Cautín                  20.3
                                                 Malleco                 22.3
10.0   Los Lagos                                 Llanquihue              23.9
                                                 Chiloé                  19.5
                                                 Osorno                  17.0
                                                 Palena                  13.6
11.0   Aysén del General Carlos Ibáñez del Campo Coyhaique               31.0
                                                 Aysén                   10.5
                                                 Capitán Prat             0.0
                                                 General Carrera         18.8
12.0   Magallanes y de la Antártica Chilena      Magallanes              27.3
                                                 Tierra del Fuego        57.1
                                                 Última Esperanza        13.6
13.0   Metropolitana de Santiago                 Cordillera              35.1
                                                 Chacabuco               26.8
                                                 Maipo                   23.9
                                                 Melipilla               25.1
                                                 Talagante               23.4
                                                 Santiago Norte          27.4
                                                 Santiago Occidente      21.6
                                                 Santiago Central        33.6
                                                 Santiago Oriente        34.3
                                                 Santiago Sur            24.5
                                                 Santiago Sur Oriente    29.6
14.0   Los Ríos                                  Valdivia                27.9
                                                 Ranco                   17.7
15.0   Arica y Parinacota                        Arica                   25.7
                                                 Parinacota              50.0
16.0   Ñuble                                     Diguillín               22.7
                                                 Itata                   20.6
                                                 Punilla                 14.0
NaN    NaN                                       NaN                     25.2

                                                                       2015.0
Region Nombre Region                             Nombre Provincia
1.0    Tarapacá                                  Iquique                 15.3
                                                 Tamarugal               17.6
2.0    Antofagasta                               Antofagasta             23.0
                                                 El Loa                  37.1
                                                 Tocopilla               27.3
3.0    Atacama                                   Copiapó                 26.5
                                                 Chañaral                14.3
                                                 Huasco                  17.7
4.0    Coquimbo                                  Elqui                   24.5
                                                 Choapa                  16.8
                                                 Limarí                  16.7
5.0    Valparaíso                                Valparaíso              25.7
                                                 Isla de Pascua          66.7
                                                 Los Andes               25.6
                                                 Petorca                 24.3
                                                 Quillota                22.0
                                                 San Antonio             28.4
                                                 San Felipe              28.0
                                                 Marga Marga             25.2
6.0    Libertador General Bernardo O'Higgins     Cachapoal               27.0
                                                 Cardenal Caro           28.8
                                                 Colchagua               23.3
7.0    Maule                                     Talca                   24.0
                                                 Cauquenes               19.0
                                                 Curicó                  25.3
                                                 Linares                 24.7
8.0    Biobío                                    Concepción              26.3
                                                 Arauco                  25.1
                                                 Bíobío                  23.5
9.0    La Araucanía                              Cautín                  26.2
                                                 Malleco                 24.9
10.0   Los Lagos                                 Llanquihue              31.6
                                                 Chiloé                  19.9
                                                 Osorno                  27.1
                                                 Palena                  16.7
11.0   Aysén del General Carlos Ibáñez del Campo Coyhaique               34.1
                                                 Aysén                   24.4
                                                 Capitán Prat            33.3
                                                 General Carrera         18.2
12.0   Magallanes y de la Antártica Chilena      Magallanes              33.8
                                                 Tierra del Fuego         0.0
                                                 Última Esperanza        13.0
13.0   Metropolitana de Santiago                 Cordillera              43.3
                                                 Chacabuco               29.9
                                                 Maipo                   31.2
                                                 Melipilla               23.2
                                                 Talagante               17.8
                                                 Santiago Norte          28.0
                                                 Santiago Occidente      27.3
                                                 Santiago Central        36.3
                                                 Santiago Oriente        36.0
                                                 Santiago Sur            28.3
                                                 Santiago Sur Oriente    29.8
14.0   Los Ríos                                  Valdivia                28.9
                                                 Ranco                   28.1
15.0   Arica y Parinacota                        Arica                   26.8
                                                 Parinacota             100.0
16.0   Ñuble                                     Diguillín               25.6
                                                 Itata                   30.8
                                                 Punilla                 19.7
NaN    NaN                                       NaN                     27.7